### GET /

GET http://localhost:3000/ HTTP/1.1

### GET /items

GET http://localhost:3000/tasks HTTP/1.1

### POST /items

POST http://localhost:3000/tasks HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "title": "",
    "completed": false
}

### PUT /items/:id

PUT http://localhost:3000/tasks/1 HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "title": "",
    "completed": true
}

### DELETE /items/:id

DELETE http://localhost:3000/tasks/1 HTTP/1.1